#!/usr/bin/env python3
"""Free narration with word-level timing: labels land on the words that name them, subtitles and an .srt come for free.

    python3 narrate.py <film>.html                     # reads <film>-vo/script.json, writes the NARRATION block + <film>-vo/<film>.srt
    python3 narrate.py <film>.html --check             # only verify the block already in the film (fits, marks resolve, 0 page errors)

<film>-vo/script.json:
    {"voice": "zh-CN-XiaoxiaoNeural", "rate": "-8%",
     "lines": [{"shot": 1, "text": "植物需要三样东西：{SUN}阳光、{WATER}水，和{CO2}二氧化碳。", "lead": 0.2}]}

- One line per shot (a shot may have none). `lead` = seconds after shot.t0 the voice starts (default 0.15).
- {FIELD} is a bookmark: shot N's own cue field FIELD (e.g. `SUN: .5` in the shot object) is set, at boot, to the time
  the next word is spoken. The field must already exist in that shot; write its old value as the fallback.
- Voice is Microsoft Edge online TTS via the `edge-tts` package: free, no key, needs network. Clips are cached by text+voice+rate.
- Fails (exit 1) when a line would run past its shot's end, a mark names a missing field, or the page throws.
"""
import argparse
import asyncio
import base64
import functools
import hashlib
import http.server
import json
import re
import socketserver
import subprocess
import sys
import threading
import urllib.parse
from pathlib import Path

MARK = re.compile(r"\{(\w+)\}")
BREAK = "，。！？；：、,.!?;:"
BEGIN, END = "// ═══ NARRATION (generated by narrate.py — edit <film>-vo/script.json, not this block)", "// ═══ /NARRATION"
TAIL = 0.1  # the voice must end this long before the cut


def serve(root: Path):
    class Quiet(http.server.SimpleHTTPRequestHandler):
        def log_message(self, *a):
            pass
    srv = socketserver.TCPServer(("127.0.0.1", 0), functools.partial(Quiet, directory=str(root)))
    threading.Thread(target=srv.serve_forever, daemon=True).start()
    return srv, srv.server_address[1]


async def probe(film: Path) -> dict:
    """Load the film headless: shot spans + cue fields, the marks as applied, page errors."""
    from playwright.async_api import async_playwright
    srv, port = serve(film.parent)
    try:
        async with async_playwright() as p:
            try:
                b = await p.chromium.launch(channel="chrome")
            except Exception:
                b = await p.chromium.launch()
            pg = await b.new_page()
            errs = []
            pg.on("pageerror", lambda e: errs.append(str(e)))
            await pg.goto(f"http://127.0.0.1:{port}/{urllib.parse.quote(film.name)}?ui=0")
            try:
                await pg.wait_for_function("window.__READY === true", timeout=15000)
            except Exception:
                errs.append("film never became ready (boot threw?)")
            info = await pg.evaluate("""() => ({ size: typeof W === 'undefined' ? [16, 9] : [W, H],
                shots: typeof SHOTS === 'undefined' ? [] : SHOTS.map(s => ({ name: s.name, t0: s.t0, t1: s.t1,
                    fields: Object.keys(s).filter(k => /^[A-Z][A-Z0-9_]*$/.test(k) && typeof s[k] === 'number') })),
                narr: window.__film && window.__film.narr ? window.__film.narr() : null })""")
            await b.close()
    finally:
        srv.shutdown()
    info["errors"] = errs
    return info


async def tts(text: str, voice: str, rate: str, out: Path) -> list:
    """Synthesise one clip; return [(start_s, end_s, word)] from the service's word boundaries."""
    import edge_tts
    words, audio = [], bytearray()
    for attempt in range(3):
        try:
            words.clear(); audio.clear()
            async for ch in edge_tts.Communicate(text, voice, rate=rate, boundary="WordBoundary").stream():
                if ch["type"] == "audio":
                    audio += ch["data"]
                elif ch["type"] == "WordBoundary":
                    words.append((ch["offset"] / 1e7, (ch["offset"] + ch["duration"]) / 1e7, ch["text"]))
            break
        except Exception as e:  # the free service drops connections now and then
            if attempt == 2:
                raise RuntimeError(f"edge-tts failed 3× for {text[:20]!r}: {e}") from e
    out.write_bytes(bytes(audio))
    return words


def duration(p: Path) -> float:
    r = subprocess.run(["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", str(p)], capture_output=True, text=True, check=True)
    return float(r.stdout)


def align(spoken: str, words: list) -> list:
    """Char span of every boundary word inside the spoken text: [(a, b, start, end)]."""
    out, cur = [], 0
    for s, e, w in words:
        i = spoken.find(w, cur)
        if i < 0:
            continue
        out.append((i, i + len(w), s, e))
        cur = i + len(w)
    return out


def phrases(spoken: str, spans: list, maxlen: int) -> list:
    """Split a line into subtitle phrases at punctuation (and at word edges when too long): [(a, b, t0, t1)] local times."""
    out, a, first = [], None, None
    for k, (wa, wb, s, e) in enumerate(spans):
        if a is None:
            a, first = wa, s
        nxt = spans[k + 1][0] if k + 1 < len(spans) else len(spoken)
        tail = spoken[wb:nxt]
        grow = spans[k + 1][1] - a if k + 1 < len(spans) else 0
        if any(c in BREAK for c in tail) or k + 1 == len(spans) or grow > maxlen:
            out.append((a, wb + len(tail.rstrip()) if any(c in BREAK for c in tail) else wb, first, e))
            a = None
    return out


def build(script: dict, shots: list, size: tuple, vo: Path) -> tuple:
    voice, rate = script.get("voice", "zh-CN-XiaoxiaoNeural"), script.get("rate", "+0%")
    lines, ev, subs, marks, src, errs, report = [], [], [], {}, [], [], []
    maxlen = 16 if size[0] > size[1] else 11   # subtitle chars per phrase: landscape vs portrait/square
    for n, ln in enumerate(script["lines"]):
        si = ln["shot"]
        if not 1 <= si <= len(shots):
            errs.append(f"line {n + 1}: shot {si} does not exist"); continue
        sh = shots[si - 1]
        raw = ln["text"]
        spoken, idx = "", []
        pos = 0
        for m in MARK.finditer(raw):
            spoken += raw[pos:m.start()]
            idx.append((m.group(1), len(spoken)))
            pos = m.end()
        spoken += raw[pos:]
        for fld, _ in idx:
            if fld not in sh["fields"]:
                errs.append(f"line {n + 1}: shot {si} ({sh['name']}) has no numeric cue field {fld} — add `{fld}: <fallback s>` to the shot")
        key = hashlib.sha1(f"{voice}|{rate}|{spoken}".encode()).hexdigest()[:10]
        mp3, wj = vo / f"line{n + 1:02d}-{key}.mp3", vo / f"line{n + 1:02d}-{key}.json"
        if mp3.exists() and wj.exists():
            words = json.loads(wj.read_text())
        else:
            words = asyncio.run(tts(spoken, voice, rate, mp3))
            wj.write_text(json.dumps(words, ensure_ascii=False))
        spans = align(spoken, words)
        if not spans:
            errs.append(f"line {n + 1}: no word boundaries came back"); continue
        dur = duration(mp3)
        t = sh["t0"] + ln.get("lead", .15)
        end_voice = t + spans[-1][3]
        room = sh["t1"] - TAIL - t
        if end_voice > sh["t1"] - TAIL:
            cps = len(re.sub(r"\W", "", spoken)) / spans[-1][3]
            errs.append(f"line {n + 1}: speech ends {end_voice:.2f}s but shot {si} cuts at {sh['t1']:g}s — cut ~{int((end_voice - sh['t1'] + TAIL) * cps) + 1} chars "
                        f"(room {room:.2f}s at {cps:.1f} chars/s)")
        li = len(lines)
        lines.append(spoken)
        src.append(base64.b64encode(mp3.read_bytes()).decode())
        ev.append({"t": round(t, 3), "k": "vo", "id": li, "dur": round(min(dur, sh["t1"] - t), 3),
                   "said": [round(t + spans[0][2], 3), round(end_voice, 3)]})   # first word start, last word end (pacing checks)
        for fld, ci in idx:
            w = next((s for a, b, s, e in spans if b > ci), spans[-1][2])
            marks[f"S{si}.{fld}"] = round(t + w, 3)
        ph = phrases(spoken, spans, maxlen)
        for k, (a, b, t0, t1) in enumerate(ph):
            hold = ph[k + 1][2] if k + 1 < len(ph) else t1 + .35
            subs.append([round(t + t0, 3), round(min(t + hold, sh["t1"]), 3), li, a, b])
        report.append((si, spoken, t, end_voice, sh["t1"], [(f, marks[f"S{si}.{f}"]) for f, _ in idx]))
    return {"lines": lines, "ev": ev, "subs": subs, "marks": marks, "src": src}, errs, report


def block(n: dict) -> str:
    j = lambda o: json.dumps(o, ensure_ascii=False, separators=(",", ":"))
    return (f"{BEGIN}\nObject.assign(NARR, {{ lines: {j(n['lines'])},\n  ev: {j(n['ev'])},\n  subs: {j(n['subs'])},\n  marks: {j(n['marks'])} }});\n"
            f"VO.src = {j(n['src'])};\n{END}\n")


def write_block(html: str, b: str) -> str:
    if BEGIN.split(" (")[0] in html:
        return re.sub(re.escape(BEGIN.split(" (")[0]) + r".*?" + re.escape(END) + r"\n", lambda _: b, html, flags=re.S)
    i = html.find("// ═══ ENGINE", html.find("// ═══ STORY"))
    if i < 0:
        sys.exit("film has no `// ═══ STORY` … `// ═══ ENGINE` section")
    return html[:i] + b + "\n" + html[i:]


def srt(n: dict) -> str:
    ts = lambda x: f"{int(x // 3600):02d}:{int(x % 3600 // 60):02d}:{int(x % 60):02d},{int(round(x % 1 * 1000)) % 1000:03d}"
    return "".join(f"{k}\n{ts(a)} --> {ts(b)}\n{n['lines'][li][x:y].rstrip(BREAK)}\n\n" for k, (a, b, li, x, y) in enumerate(n["subs"], 1))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("film", type=Path)
    ap.add_argument("--script", type=Path, help="default <film>-vo/script.json")
    ap.add_argument("--check", action="store_true", help="verify the film as it is; write nothing")
    a = ap.parse_args()
    film = a.film.resolve()
    vo = film.with_name(film.stem + "-vo")
    if not a.check:
        script = json.loads((a.script or vo / "script.json").read_text())
        info = asyncio.run(probe(film))
        if info["errors"]:
            print("page errors before narration:", info["errors"]); return 1
        n, errs, report = build(script, info["shots"], info["size"], vo)
        for si, text, t, e, t1, mk in report:
            print(f"  shot {si} {t:6.2f}–{e:6.2f}s (cut {t1:g}) {text}" + ("".join(f"  [{f}@{x:.2f}]" for f, x in mk)))
        if errs:
            for e in errs:
                print("  " + e)
            print("NARRATE FAIL"); return 1
        film.write_text(write_block(film.read_text(), block(n)))
        (vo / f"{film.stem}.srt").write_text(srt(n))
        print(f"{len(n['lines'])} lines · {len(n['subs'])} subtitle phrases · {len(n['marks'])} marks → {film.name}, {vo.name}/{film.stem}.srt")
    info = asyncio.run(probe(film))
    narr = info.get("narr") or {}
    bad = [f"mark {k} did not apply (cue = {v})" for k, v in narr.get("cues", []) if v is None] + info["errors"]
    over = []
    html = film.read_text()
    m = re.search(r"Object\.assign\(NARR, \{ lines: (.*?),\n  ev: (.*?),\n", html, re.S)
    if m:
        for e in json.loads(m.group(2)):
            sh = next((s for s in info["shots"] if s["t0"] <= e["t"] < s["t1"]), None)
            if sh and e["t"] + e["dur"] > sh["t1"] + 1e-6:
                over.append(f"voice {e['id']} runs past the cut at {sh['t1']:g}s")
    for x in bad + over:
        print("  " + x)
    print(f"marks applied: {len(narr.get('cues', []))} · subtitles: {narr.get('subs', 0)} · page errors: {info['errors'] or 'none'}")
    print("NARRATE " + ("FAIL" if bad or over else "PASS"))
    return 1 if bad or over else 0


if __name__ == "__main__":
    sys.exit(main())
